name: manual
on: 
  workflow_dispatch:
    # inputs:
    #   greeting:
    #     type: string
    #     default: hello
    #     required: true
    #     description: A ch world
    #   loglevel:
    #     description: choise test
    #     type: choice
    #     options:
    #       - info
    #       - warn
    #       - error
env:
  id: 8952
  test_id: ${{ env.id }}
jobs:
  run:
    # uses: siroponn/test-workflow-call/.github/workflows/callable.yaml@main
    runs-on: ubuntu-latest
    steps:
      - run: echo "${test_id}"

